CREATE DATABASE metricmind_db;

USE DATABASE metricmind_db;

CREATE SCHEMA raw;

CREATE SCHEMA analytics;

CREATE WAREHOUSE compute_wh
WITH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

SHOW DATABASES;
SHOW SCHEMAS;
SHOW WAREHOUSES;
